version: "3"

services:
  tmbark-notifier-car1:
    image: tmbark-notifier:local
    container_name: tmbark-notifier-car1
    restart: always
    env_file:
      - ./.env.docker
    environment:
      CAR_ID: "1"
      PUBLIC_BASE_URL: http://your-synology-lan-ip:18080
    ports:
      - "18080:8080"

  tmbark-notifier-car2:
    image: tmbark-notifier:local
    container_name: tmbark-notifier-car2
    restart: always
    env_file:
      - ./.env.docker
    environment:
      CAR_ID: "2"
      PUBLIC_BASE_URL: http://your-synology-lan-ip:18081
    ports:
      - "18081:8080"
